import { invoke } from "@tauri-apps/api/tauri";
import { open } from "@tauri-apps/api/dialog";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import * as fs from "@tauri-apps/api/fs";

// TODO:windowsだとパス変換が必要
const SMAPLE_IMAGE_DIR =
  "/Users/shuntaka/repos/github.com/shuntaka9576/tauri-sandbox/_testdata/images";
const SAMPLE_IMAGE_FILE = "13cea.JPG";

interface ImageFile {
  name?: string;
  path?: string;
}

const Home = () => {
  const [appImageDirPath, setAppImageDir] = useState<string>("");
  const [imageFiles, setImageFiles] = useState<ImageFile[]>([]);
  const openDialog = () => {
    open().then((files) => console.log(files));
  };

  const executeCommands = () => {
    invoke("simple_commnad");
  };

  useEffect(() => {
    (async () => {
      const { path } = await import("@tauri-apps/api");
      // path系のAPI
      const appDir = await path.appDir();

      // _testdataのファイルをコピーする
      await fs.createDir("images", {
        dir: fs.BaseDirectory.App,
        recursive: true,
      });
      const appImageDirPath = await path.join(appDir, "images");
      const appImagesSampleFilePath = await path.join(
        appImageDirPath,
        SAMPLE_IMAGE_FILE
      );
      const sampleImageFilePath = await path.join(
        SMAPLE_IMAGE_DIR,
        SAMPLE_IMAGE_FILE
      );
      setAppImageDir(appImageDirPath);

      await fs.copyFile(sampleImageFilePath, appImagesSampleFilePath, {});
    })();
  }, []);

  useEffect(() => {
    console.log("render!");
    (async () => {
      if (appImageDirPath !== "") {
        const files = await fs.readDir(appImageDirPath);
        setImageFiles(files);
        console.log(`app image files: ${JSON.stringify(files)}`);
      }
    })();
  }, [appImageDirPath]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl text-black-300 font-bold">tauri-sandbox</h1>
        <div className="pb-2">
          <h2 className="font-bold">Command</h2>
          <div>invoke rust command</div>
          <button
            className="rounded-md border border-transparent bg-indigo-600 px-1 py-1 text-base font-medium text-white hover:bg-indigo-700"
            onClick={executeCommands}
          >
            invoke
          </button>
        </div>

        <div className="pb-2">
          <h2 className="font-bold">Tauri API</h2>
          <div>open dialog</div>
          <button
            className="rounded-md border border-transparent bg-indigo-600 px-1 py-1 text-base font-medium text-white hover:bg-indigo-700"
            onClick={openDialog}
          >
            openDialog
          </button>
          <div>get local image</div>
          <p>appImageDirPath:{appImageDirPath}</p>
          <ul>
            {imageFiles.map((imageFile, index) => {
              return <li key={index}>{imageFile.path}</li>;
            })}
          </ul>
        </div>
      </main>
    </div>
  );
};

export default Home;
