import { invoke } from "@tauri-apps/api/tauri";
import { open } from "@tauri-apps/api/dialog";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const openDialog = () => {
    open().then((files) => console.log(files));
  };

  const executeCommands = () => {
    const isClient = typeof window !== "undefined";
    isClient && invoke("simple_commnad");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>exec rust code</div>
        <button onClick={executeCommands}>Clickt execute command</button>
        <div>open dialog</div>
        <button onClick={openDialog}>openDialog</button>
      </main>
    </div>
  );
};

export default Home;
